apiVersion: apps/v1
kind: Deployment
metadata:
  name: pizzaordermanagement
  labels:
    app: pizzaordermanagement
spec:
  replicas: 4
  selector:
    matchLabels:
      app: pizzaordermanagement
  template:
    metadata:
      labels:
        app: pizzaordermanagement
    spec:
      containers:
        - name: pizzaordermanagement
          image: skcc02acr.azurecr.io/pizzaordermanagement:latest
          ports:
            - containerPort: 8080