apiVersion: v1
kind: Service
metadata:
  name: pizzaordermanagement
  labels:
    app: pizzaordermanagement
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: pizzaordermanagement
